#!/usr/bin/env python3
import requests
import json
import time

def test_fixed_multiround():
    """Test fixed multi-round generation issue"""
    print("🔧 Testing fixed multi-round ReAct loops...")
    
    url = "http://localhost:8000/react_solve"
    headers = {
        "Content-Type": "application/json",
        "x-project-id": "test123",
        "x-project-name": "ancient_temple"
    }
    data = {
        "problem": "Search for information about ancient temple architecture",
        "project_context": {
            "project_id": "test123",
            "project_name": "ancient_temple"
        }
    }
    
    print("🚀 Sending test request...")
    print("📋 Problem:", data["problem"])
    print("="*60)
    
    try:
        start_time = time.time()
        response = requests.post(url, headers=headers, json=data, timeout=120)
        end_time = time.time()
        
        print(f"⏱️ Processing time: {end_time - start_time:.2f}s")
        print(f"📊 Status code: {response.status_code}")
        
        if response.status_code == 200:
            result = response.json()
            print("✅ Request successful!")
            
            # Analyze thinking_process
            thinking_process = result.get('thinking_process', [])
            print(f"\n🧠 Thinking process analysis ({len(thinking_process)} rounds):")
            
            for i, step in enumerate(thinking_process, 1):
                print(f"\n--- Round {i} ---")
                
                if step.get('thought'):
                    print(f"💭 Thought: {step['thought'][:80]}...")
                else:
                    print("💭 Thought: [None]")
                
                if step.get('action'):
                    print(f"🔧 Action: {step['action']}")
                    if step.get('action_input'):
                        try:
                            action_input = json.loads(step['action_input']) if isinstance(step['action_input'], str) else step['action_input']
                            print(f"📋 Action Input: {json.dumps(action_input)}")
                        except:
                            print(f"📋 Action Input: {step['action_input']}")
                else:
                    print("🔧 Action: [None]")
                
                if step.get('observation'):
                    obs_preview = step['observation'][:100] + "..." if len(step['observation']) > 100 else step['observation']
                    print(f"👁️  Observation: {obs_preview}")
                else:
                    print("👁️  Observation: [None]")
                
                if step.get('final_answer'):
                    answer_preview = step['final_answer'][:100] + "..." if len(step['final_answer']) > 100 else step['final_answer']
                    print(f"🎯 Final Answer: {answer_preview}")
            
            # Show final answer
            final_content = result.get('content', [{}])[0].get('text', '')
            print(f"\n📝 Final response:")
            print(final_content)
            
            # Verify multi-round execution
            action_count = sum(1 for step in thinking_process if step.get('action'))
            print(f"\n📊 Statistics:")
            print(f"- Total rounds: {len(thinking_process)}")
            print(f"- Tool calls: {action_count}")
            print(f"- Real multi-round execution: {'✅ Yes' if action_count > 1 else '❌ No'}")
            
        else:
            print(f"❌ Request failed: {response.text}")
            
    except Exception as e:
        print(f"❌ Request error: {e}")

def test_health():
    """Check service health"""
    try:
        response = requests.get("http://localhost:8000/health", timeout=5)
        print(f"🏥 Service status: {response.status_code}")
        if response.status_code == 200:
            health_data = response.json()
            print(f"✅ Service running, uptime: {health_data.get('uptime', 0):.1f}s")
            return True
    except Exception as e:
        print(f"❌ Service unavailable: {e}")
        return False

if __name__ == "__main__":
    print("🚀 Starting test for fixed multi-round ReAct...")
    
    # 1. Check service status
    if not test_health():
        print("⚠️ Please ensure FastAPI service is running")
        exit(1)
    
    # 2. Test fixed functionality  
    test_fixed_multiround()
    
    print("\n🎉 Test completed!")
    print("\n💡 Expected results:")
    print("- Should see multiple real tool calls")
    print("- Each round should have real Observation")
    print("- No fake Observations generated by LLM")
    print("- Server should show detection and fix logs for fake Observations") 